baseURL = '/'
languageCode = 'en-us'
title = 'Alejandro Garcia Serna'

[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"

[params]
color = 'linen' # linen, wheat, gray, light

# header social icons
twitter = 'alejogs4'                          # twitter.com/YOUR_TWITTER_ID
github = 'alejogs4'                           # github.com/YOUR_GITHUB_ID
linkedin = 'alejandro-garcia-serna-531093156' # linkedin.com/in/YOUR_LINKEDIN_ID

# home page profile
avatar = 'https://avatars.githubusercontent.com/u/21073419?v=4'
name = 'Alejandro Garcia Serna'
bio = 'Software Engineer'


# misc
disableHLJS = false           # disable highlight.js
disablePostNavigation = true  # disable post navigation
monoDarkIcon = true           # show monochrome dark mode icon
math = false                  # enable KaTeX math typesetting globally
localKatex = false            # use local KaTeX js/css instead of CDN
favicon = "favicon-96x96.png" # customize the default favicon
direction = "ltr"
mainSections = ["posts"]      # sections to show on homepage
